name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      artist_name:
        description: 'Artist Name'
        required: true

jobs:
  run_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Update apt packages and install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run upload.py
      run: python upload.py ${{ github.event.inputs.artist_name }}

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add index.html
        git commit -m "Update index.html for ${{ github.event.inputs.artist_name }}"
        git push
